import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import NFT from './nft'

export default function Home() {
  const [feed, setFeed] = useState([]);



  useEffect(() => {

    const mockedData = [
      {
        image: 'https://studentedgeapplication.azureedge.net/articles/af917662-3be9-4009-b5d0-194dc8cdd55a.jpg',
        caption: 'This is a succinct caption',
        owner: 'Esteban',
        price: '0.5',
        uuid: '98fs080f9s8',
        userId: '1',
        author: 'Kanye West'
      },
      {
        image: 'https://static.theceomagazine.net/wp-content/uploads/2021/07/29092208/jay-z.jpg',
        caption: 'On the other hand this is a very long caption, we want to see how this renders in the view you know? Hahahaha what a long caption dude.',
        owner: '',
        price: '0.8',
        uuid: '98fs080f9s8',
        userId: '1',
        author: 'Jay Z'
      }
    ]

    setFeed(mockedData)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          OnlyFung
        </h1>

        {feed?.map(nft => {
          return(
            <NFT
              key = {nft.uuid}
              author = {nft.author}
              imageUrl = {nft.image}
              owner = {nft.owner}
              price = {nft.price}
              caption = {nft.caption}
            />
          )
        })}
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
