import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import NFT from './nft'
import Navbar from '../components/Navbar';

export default function Home() {
  const [feed, setFeed] = useState([]);



  useEffect(() => {

    const mockedData = [
      {
        image: 'https://thumbor.forbes.com/thumbor/fit-in/416x416/filters%3Aformat%28jpg%29/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F5ed00f17d4a99d0006d2e738%2F0x0.jpg%3Fbackground%3D000000%26cropX1%3D154%26cropX2%3D4820%26cropY1%3D651%26cropY2%3D5314',
        caption: 'This is a succinct caption',
        owner: 'Esteban',
        price: '0.5',
        uuid: '98fs080f9s8',
        userId: '1',
        author: 'Kanye West'
      },
      {
        image: 'https://static.theceomagazine.net/wp-content/uploads/2021/07/29092208/jay-z.jpg',
        caption: 'On the other hand this is a very long caption, we want to see how this renders in the view you know? Hahahaha what a long caption dude.',
        owner: '',
        price: '0.8',
        uuid: '98fs080f9s8',
        userId: '1',
        author: 'Jay Z'
      }
    ]

    setFeed(mockedData)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <Navbar/>
      <br/>

      <main className={styles.main}>      
        {feed?.map(nft => {
          return(
            <NFT
              key = {nft.uuid}
              author = {nft.author}
              imageUrl = {nft.image}
              owner = {nft.owner}
              price = {nft.price}
              caption = {nft.caption}
            />
          )
        })}
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
