import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';

export default function Home() {
  const [feed, setFeed] = useState([]);



  useEffect(() => {

    const mockedData = [
      {
        image: 'sjklfsjf',
        caption: 'This is a succinct caption',
        owner: 'Esteban',
        price: 'Ξ 0.5',
        uuid: '98fs080f9s8',
        userId: '1',
        author: 'Kanye West'
      },
      {
        image: 'sjklfsjf',
        caption: 'On the other hand this is a very long caption, we want to see how this renders in the view you know? Hahahaha what a long caption dude.',
        owner: '',
        price: 'Ξ 0.8',
        uuid: '98fs080f9s8',
        userId: '1',
        author: 'Jay Z'
      }
    ]

    setFeed(mockedData)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          OnlyFung
        </h1>

        {feed?.map(nft => {
          return(
            <div key={nft.uuid}>
              <p >{nft.author}</p>
              <p>{nft.image}</p>
              {nft.owner && 
                <p>Owned by <strong>{nft.owner}</strong></p>
              }
              <p>{nft.price}</p>
            </div>
          )
        })}
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
